version: '3'
services:
  api:
    image: api-car-dealer-project
    build: .
    ports:
      - "5025:3005"
    volumes:
      - ./:/usr/src/api-car-dealer-project
    depends_on: 
      - postgres
  postgres:
    image: postgres
    ports: 
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: backend-test